#!/usr/bin/env npx tsx

import { readFileSync } from "node:fs";
import { join } from "node:path";

const PROJECT_ROOT = join(__dirname, "..");
const KB_ROOT = join(PROJECT_ROOT, "knowledge-base");
const META = join(KB_ROOT, "meta");

// ─── Helpers ──────────────────────────────────────────────────────────

function readOptional(path: string): string | null {
  try {
    return readFileSync(path, "utf-8");
  } catch {
    return null;
  }
}

function extractSection(md: string, heading: string): string {
  const lines = md.split("\n");
  const startIdx = lines.findIndex((l) => l.startsWith(`## ${heading}`));
  if (startIdx === -1) return "";

  const body: string[] = [];
  for (let i = startIdx + 1; i < lines.length; i++) {
    if (lines[i].startsWith("## ")) break;
    body.push(lines[i]);
  }
  return body.join("\n").trim();
}

// ─── Main ─────────────────────────────────────────────────────────────

function main(): void {
  console.log("╔══════════════════════════════════════╗");
  console.log("║         Zuhn — Morning Briefing      ║");
  console.log("╚══════════════════════════════════════╝");
  console.log("");

  // 1. Session state
  const sessionMd = readOptional(join(META, "session.md"));

  if (!sessionMd) {
    console.log("No previous session state found. Starting fresh.");
    console.log("");
  } else {
    const focusArea = extractSection(sessionMd, "Focus Area");
    const trainOfThought = extractSection(sessionMd, "Train of Thought");
    const activeFiles = extractSection(sessionMd, "Active Files");
    const openLoops = extractSection(sessionMd, "Open Loops");
    const nextActions = extractSection(sessionMd, "Next Actions");

    console.log("## Last Session");
    console.log(`Focus: ${focusArea}`);
    console.log(`Thought: ${trainOfThought}`);
    console.log("");

    if (activeFiles) {
      console.log("## Active Files");
      console.log(activeFiles);
      console.log("");
    }

    if (openLoops) {
      console.log("## Open Loops");
      console.log(openLoops);
      console.log("");
    }

    if (nextActions) {
      console.log("## Next Actions");
      console.log(nextActions);
      console.log("");
    }
  }

  // 2. Flags
  const flagsMd = readOptional(join(META, "flags.md"));
  console.log("## Flags");
  if (flagsMd) {
    // Strip the header line, show the content
    const content = flagsMd
      .replace(/^#.*\n/m, "")
      .replace(/^Generated by.*\n/m, "")
      .trim();
    console.log(content || "No flags.");
  } else {
    console.log("No flags.");
  }
  console.log("");

  // 3. Pending work
  const pendingMd = readOptional(join(META, "pending.md"));
  console.log("## Pending Work");
  if (pendingMd) {
    const content = pendingMd.replace(/^#.*\n/m, "").trim();
    console.log(content || "No pending work.");
  } else {
    console.log("No pending work.");
  }
  console.log("");

  // 4. Knowledge base stats
  const statsMd = readOptional(join(META, "stats.md"));
  console.log("## Knowledge Base Stats");
  if (statsMd) {
    // Extract the bullet-point summary lines
    const lines = statsMd
      .split("\n")
      .filter((l) => l.startsWith("- **"))
      .join("\n");
    console.log(lines || "No stats available.");
  } else {
    console.log("No stats available.");
  }
  console.log("");
}

main();
